name: PKG

on:
  pull_request:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: pnpm

      - run: pnpm install && pnpm package
      - run: pnpm publish ./package --dry-run --no-git-checks

      - uses: actions/upload-artifact@v3
        with:
          path: ./package
          retention-days: 5
