name: Release

on:
  push:
    branches:
      - "master"

jobs:
  npm-publish:
    runs-on: ubuntu-latest
    if: "contains(github.event.head_commit.message, '~ v')"
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: "https://registry.npmjs.org"
      - name: Install and compile package
        run: npm install && npm run package
      - name: Publish package
        run: npm publish ./package
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
